services:
  - type: web
    name: gamertracker
    runtime: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT web_project.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "2"
