# Generated by Django 6.0.1 on 2026-02-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gamestat_date_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestat',
            old_name='hours_played',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='gamestat',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gamestat',
            name='time_played',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
