# Generated by Django 6.0.1 on 2026-04-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gamestat_metric_1_gamestat_metric_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
    ]
