# Generated by Django 6.0.1 on 2026-04-22 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_username', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('time_played', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_score', models.FloatField(default=0.0)),
                ('m1', models.CharField(blank=True, max_length=100, null=True)),
                ('m2', models.CharField(blank=True, max_length=100, null=True)),
                ('m3', models.CharField(blank=True, max_length=100, null=True)),
                ('date_saved', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_username', 'platform')},
            },
        ),
        migrations.DeleteModel(
            name='GameStat',
        ),
    ]
