# Generated by Django 5.2 on 2026-06-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdsourcedStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_choice', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('m1', models.FloatField(default=0.0)),
                ('m2', models.FloatField(default=0.0)),
                ('m3', models.FloatField(default=0.0)),
                ('m4', models.FloatField(default=0.0)),
                ('m5', models.FloatField(default=0.0)),
                ('m6', models.FloatField(default=0.0)),
                ('m7', models.FloatField(default=0.0)),
                ('m8', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('game_choice', 'username', 'date')},
            },
        ),
    ]
