# Generated by Django 5.2 on 2026-06-21 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_crowdsourcedstatsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourcedstatsnapshot',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
